[package]
name = "lassie"
version = "0.1.0"
authors = ["Thomas Corbett - thomas.corbett.jr@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
byteorder = "1.3.4"